<?php

namespace App\Http\Middleware;

use Closure;

use Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode as Middleware;
use Illuminate\Support\Facades\Request;

class First extends Middleware
{
    public function handle($request, Closure $next)
    {
        return parent::handle($request, $next); // TODO: Change the autogenerated stub
    }

    /**
     * The URIs that should be reachable while maintenance mode is enabled.
     *
     * @var array
     */
    protected $except = [
        //
    ];
}
